from typing import Protocol
from pathlib import Path


class WaveLoggerDocumentLike(Protocol):
    @property
    def data_count(self) -> int: ...

    def get_data(self, unit_id: int, channel_id: int, pos: int) -> float | None: ...

    def get_current_data(self, unit_id: int, channel_id: int) -> float | None: ...


class WaveLoggerConnectorLike(Protocol):
    def setup_usb(self, device_id: int) -> None: ...


class WaveLoggerMeasurementLike(Protocol):
    def load_settings(self, path: Path | str) -> None: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...


class WaveLoggerAppLike(Protocol):
    @property
    def connector(self) -> WaveLoggerConnectorLike: ...

    @property
    def measurement(self) -> WaveLoggerMeasurementLike: ...

    def get_active_document(self) -> WaveLoggerDocumentLike: ...

    def __enter__(self) -> "WaveLoggerAppLike": ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
